@echo on

set "HOUDINI_PATH_BSLASH=%RR_HTOA_BASE%;%HOUDINI_PATH%;%rrBaseAppPath%\houdini"
set "HOUDINI_PATH=%HOUDINI_PATH_BSLASH:\=/%"

set "HOUDINI_OTLSCAN_PATH_BSLASH=%RR_HTOA_BASE%\otls;%HOUDINI_OTLSCAN_PATH%;%rrBaseAppPath%\houdini\otls" 
set "HOUDINI_OTLSCAN_PATH=%HOUDINI_OTLSCAN_PATH_BSLASH:\=/%"


