# Generated by RR Project Modifier 

#Header files 
HEADERS += \
    ../../shared_SDK/RR_DataTypes_jobs_SDK.h \ 
    ../../shared_SDK/RR_DataTypes_other_SDK.h \ 
    ../../shared_SDK/RR_DataTypes_plugins_SDK.h \ 
    ../../shared_SDK/RR_DataTypes_RenderApp_SDK.h \ 
    ./rrJobTester_noQT.h \ 


#Source files 
SOURCES += \
    ../../shared_SDK/RR_DataTypes_jobs_SDK.cpp \ 
    ../../shared_SDK/RR_DataTypes_other_SDK.cpp \ 
    ../../shared_SDK/RR_DataTypes_plugins_SDK.cpp \ 
    ../../shared_SDK/RR_DataTypes_RR_SDK.cpp \ 
    ../../shared_SDK/RR_files_SDK.cpp \ 
    ./rrJobTester_noQT.cpp \ 


mac {
SOURCES += \
}



#Forms 
FORMS += \


#Resource file(s) 
RESOURCES += \


